version: '3'
services:
  vocabulary-service:
    build:
      context: .
      args:
        REQUEREMENTS: requirements/test.txt
    volumes:
      - ./main:/service/main
    networks:
      2read_online:
networks:
  2read_online:
    external: true
volumes:
  models:
