version: '3'
services:
  vocabulary-service:
    build:
      context: .
      args:
        REQUEREMENTS: requirements/test.txt
    volumes:
      - ./main:/service/main
    networks:
      2read_online:
    command: uvicorn main.main:main --reload --host 0.0.0.0

networks:
  2read_online:
    external: true
