name: Release
on:
  create:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t ${{github.repository}} --build-arg BACKEND_URL=https://2read.online .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: 6dd62dddad719a592996501ba169bf90da398a37eecfde7856c73268b1018db9 # use secret when you're reach
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Set tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Tag image
        run: docker tag ${{github.repository}} registry.digitalocean.com/to-read-online/${{github.event.repository.name}}:${{ steps.vars.outputs.tag }}
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/to-read-online/${{github.event.repository.name}}:${{ steps.vars.outputs.tag }}
